sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t azimaliev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true azimaliev/docker-react yarn run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-753111453505"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY